In [1]:
from scipy.spatial import distance as dist
import numpy as np
np.random.seed(42)
objectCentroids = np.random.uniform(size=(2, 2))
centroids = np.random.uniform(size=(3, 2))
D = dist.cdist(objectCentroids, centroids)

In [2]:
D


array([[0.82421549, 0.32755369, 0.33198071],
       [0.72642889, 0.72506609, 0.17058938]])

In [3]:
D.min(axis=1)


array([0.32755369, 0.17058938])

In [4]:
rows = D.min(axis=1).argsort()
rows

array([1, 0])

In [6]:
D.argmin(axis=1)

array([1, 2])

In [5]:
cols = D.argmin(axis=1)[rows]
cols

array([2, 1])

In [11]:
inputCentroids = np.array([[8888, 666],
                           [1, 1],
                           [100, 100]])
objectCentroids = np.array([[100, 100],
                           [2, 2],
                           [7777, 666]])
D = dist.cdist(np.array(objectCentroids), inputCentroids)
rows = D.min(axis=1).argsort()
cols = D.argmin(axis=1)[rows]
print(rows, cols)

[0 1 2] [2 1 0]


In [12]:
D


array([[8.80620804e+03, 1.40007143e+02, 0.00000000e+00],
       [8.91077393e+03, 1.41421356e+00, 1.38592929e+02],
       [1.11100000e+03, 7.80438345e+03, 7.69783638e+03]])